#!/bin/bash

echo "|ATTEMPTING TO START THE VIRTUAL ENVIRONMENT"
echo "===source ./geographicallyVENV/bin/activate"
source ./geographicallyVENV/bin/activate

echo "|INSTALLING 'requirements.txt' WITH PIP3"
echo "===pip3 install -r requirements.txt"
pip3 install -q -r requirements.txt

echo "|SETTING PYTHON EVNIRONMENT VARIABLES"
echo "===export FLASK_APP=run.py"
echo "===export FLASK_ENV=development"
export FLASK_APP=run.py
export FLASK_ENV=development

echo "|ATTEMPTING TO START FLASK SERVER"
echo "===flask run --host=0.0.0.0"
flask run --host=0.0.0.0
